name: Run R Package Tests
run-name: ${{ github.actor }} triggered Github Actions
on: [ push ]

jobs:
  Run-devtools-tests:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - run: echo "ğŸ–¥ï¸ R successfully set up."

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - run: echo "ğŸ“¦ Packages successfully installed."

      - name: Run devtools::test()
        run: Rscript -e 'devtools::test()'


